name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: production
    if: ${{ github.ref == 'refs/heads/main' && github.repository_owner == 'ThisIsMissEm' }}
    permissions:
      id-token: write
      pull-requests: write
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: pnpm

      # Found this via https://github.com/tinacms/tinacms/pull/6249/files
      - name: Upgrade npm for OIDC support
        run: npm install -g npm@latest

      - name: Install Dependencies
        run: pnpm install

      - name: Create Release Pull Request or Publish to pnpm
        id: changesets
        uses: changesets/action@v1

        with:
          title: Prepare release
          commit: prepare release of packages
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm run release
          version: pnpm run version-packages
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Use OIDC for npm authentication instead of NPM_TOKEN
          NPM_TOKEN: '' # https://github.com/changesets/changesets/issues/1152#issuecomment-3190884868
